package com.dbk.puzzle;

/**
 * How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 * 
 * @author edogboo
 *
 */
public class Puzzle29 {
	public static void main(String args[]){
		
	}
	
	/**
	 * find all factors of the number
	 * @param number integer from 2 to 100;
	 * @return list of factors
	 */
	public static int[] findFactors(int number){
		return null;
	}
}
